#!/usr/bin/env node
/**
 * Writes apps/web/.env.local with API proxy settings and a reviewer requester_id
 * from the backend demo script. Requires Postgres + migrated API.
 */
import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const webRoot = path.resolve(__dirname, "..");
const apiRoot = path.resolve(webRoot, "../api");
const envPath = path.join(webRoot, ".env.local");

function checkHealth(baseUrl) {
  try {
    const response = execFileSync("curl", ["-fsS", `${baseUrl}/health`], { encoding: "utf8" });
    return response.includes("ok") || response.length > 0;
  } catch {
    return false;
  }
}

function runDemo() {
  const pythonBin = existsSync(path.join(apiRoot, ".venv/bin/python"))
    ? path.join(apiRoot, ".venv/bin/python")
    : "python3";
  const output = execFileSync(
    pythonBin,
    ["-m", "app.scripts.demo"],
    { cwd: apiRoot, encoding: "utf8" },
  );
  const payload = JSON.parse(output);
  return payload.research_experience?.reviewer_id ?? null;
}

const apiBase = process.env.VITE_API_BASE_URL ?? "http://127.0.0.1:8000";

if (!checkHealth(apiBase)) {
  console.error(
    `API is not reachable at ${apiBase}. Start Postgres/Redis and the API first:\n` +
      "  docker compose up -d postgres redis api\n" +
      "  cd apps/api && python3 -m alembic upgrade head",
  );
  process.exit(1);
}

const reviewerId = runDemo();
if (!reviewerId) {
  console.error("Demo script did not return research_experience.reviewer_id");
  process.exit(1);
}

const contents = [
  "# Generated by scripts/sync-api-env.mjs",
  "VITE_API_BASE_URL=/api",
  `VITE_REQUESTER_ID=${reviewerId}`,
  "",
].join("\n");

writeFileSync(envPath, contents, "utf8");
console.log(`Wrote ${envPath}`);
console.log(`Reviewer requester_id: ${reviewerId}`);
console.log("Run `npm run dev` in apps/web to use API mode through the Vite proxy.");
