import type { ExportRecord, Observation, SamplingCell } from './types';

export const observations: Observation[] = [
  {
    id: 'OBS-2025-548721',
    commonName: 'Emerald Ash Borer',
    scientificName: 'Agrilus planipennis',
    location: 'Delaware River Basin, PA',
    region: 'PA',
    latitude: 40.611,
    longitude: -75.184,
    submittedAt: 'May 31, 2025 10:42 AM',
    confidence: 82,
    verificationStatus: 'Unverified',
    signalScore: 78,
    signalLabel: 'Priority ecological signal',
    source: 'iNaturalist',
    privacy: 'obscured',
    coordinateUncertaintyM: 120,
    habitat: 'Forest edge',
    distanceToWaterM: 120,
    samplingLabel: 'High-risk under-sampled',
    evidenceCount: 4,
  },
  {
    id: 'OBS-2025-548719',
    commonName: 'Purple Loosestrife',
    scientificName: 'Lythrum salicaria',
    location: 'Wetland edge, NJ',
    region: 'NJ',
    latitude: 40.973,
    longitude: -74.887,
    submittedAt: 'May 31, 2025 9:15 AM',
    confidence: 42,
    verificationStatus: 'Needs more evidence',
    signalScore: 61,
    signalLabel: 'High-value verification candidate',
    source: 'User submitted',
    privacy: 'obscured',
    coordinateUncertaintyM: 80,
    habitat: 'Wetland edge',
    distanceToWaterM: 45,
    samplingLabel: 'Likely false absence',
    evidenceCount: 2,
  },
  {
    id: 'OBS-2025-548718',
    commonName: 'Spotted Lanternfly',
    scientificName: 'Lycorma delicatula',
    location: 'Urban greenbelt, PA',
    region: 'PA',
    latitude: 40.793,
    longitude: -75.012,
    submittedAt: 'May 30, 2025 6:28 PM',
    confidence: 79,
    verificationStatus: 'Unverified',
    signalScore: 73,
    signalLabel: 'High-value verification candidate',
    source: 'User submitted',
    privacy: 'public',
    coordinateUncertaintyM: 30,
    habitat: 'Urban greenbelt',
    distanceToWaterM: 360,
    samplingLabel: 'Road/trail-biased',
    evidenceCount: 3,
  },
  {
    id: 'OBS-2025-548717',
    commonName: 'Japanese Knotweed',
    scientificName: 'Fallopia japonica',
    location: 'Riparian corridor, NY',
    region: 'NY',
    latitude: 41.144,
    longitude: -74.912,
    submittedAt: 'May 30, 2025 3:10 PM',
    confidence: 63,
    verificationStatus: 'Unverified',
    signalScore: 56,
    signalLabel: 'High-value verification candidate',
    source: 'User submitted',
    privacy: 'obscured',
    coordinateUncertaintyM: 95,
    habitat: 'Riparian corridor',
    distanceToWaterM: 22,
    samplingLabel: 'Under-sampled',
    evidenceCount: 2,
  },
  {
    id: 'OBS-2025-548716',
    commonName: 'Water Chestnut',
    scientificName: 'Trapa natans',
    location: 'Slow water channel, NY',
    region: 'NY',
    latitude: 41.038,
    longitude: -74.737,
    submittedAt: 'May 29, 2025 1:05 PM',
    confidence: 68,
    verificationStatus: 'Expert verified',
    signalScore: 48,
    signalLabel: 'Moderate signal',
    source: 'Seeded demo data',
    privacy: 'public',
    coordinateUncertaintyM: 20,
    habitat: 'Slow water channel',
    distanceToWaterM: 8,
    samplingLabel: 'Well sampled',
    evidenceCount: 5,
  },
  {
    id: 'OBS-2025-548715',
    commonName: 'Garlic Mustard',
    scientificName: 'Alliaria petiolata',
    location: 'Trail edge, PA',
    region: 'PA',
    latitude: 40.858,
    longitude: -75.298,
    submittedAt: 'May 29, 2025 11:22 AM',
    confidence: 71,
    verificationStatus: 'Needs more evidence',
    signalScore: 66,
    signalLabel: 'High-value verification candidate',
    source: 'iNaturalist',
    privacy: 'obscured',
    coordinateUncertaintyM: 70,
    habitat: 'Trail edge',
    distanceToWaterM: 210,
    samplingLabel: 'Road/trail-biased',
    evidenceCount: 1,
  },
];

export const samplingCells: SamplingCell[] = [
  {
    id: '18T WL 350 545',
    category: 'High-risk under-sampled',
    priority: 'High',
    habitatSuitability: 0.84,
    samplingEffort: 0.08,
    detections: 0,
    confidence: 'Low',
  },
  {
    id: '18T WL 345 550',
    category: 'Likely false absence',
    priority: 'High',
    habitatSuitability: 0.72,
    samplingEffort: 0.12,
    detections: 0,
    confidence: 'Low',
  },
  {
    id: '18T WL 355 540',
    category: 'Under-sampled',
    priority: 'Medium',
    habitatSuitability: 0.61,
    samplingEffort: 0.21,
    detections: 1,
    confidence: 'Medium',
  },
  {
    id: '18T WL 360 555',
    category: 'Road/trail-biased',
    priority: 'Medium',
    habitatSuitability: 0.48,
    samplingEffort: 0.67,
    detections: 3,
    confidence: 'Medium',
  },
  {
    id: '18T WL 340 535',
    category: 'Park/protected-area biased',
    priority: 'Low',
    habitatSuitability: 0.31,
    samplingEffort: 0.74,
    detections: 5,
    confidence: 'High',
  },
];

export const exportHistory: ExportRecord[] = [
  {
    id: 'EXP-2025-001',
    name: 'Priority ecological signals - May 2025',
    format: 'CSV',
    filters: 5,
    records: 1246,
    status: 'Completed',
    requested: 'May 31, 2025 10:42 AM',
  },
  {
    id: 'EXP-2025-002',
    name: 'Delaware River Basin - all species',
    format: 'GeoJSON',
    filters: 4,
    records: 3812,
    status: 'Completed',
    requested: 'May 28, 2025 3:15 PM',
  },
  {
    id: 'EXP-2025-003',
    name: 'Potential corridor review',
    format: 'CSV',
    filters: 6,
    records: 645,
    status: 'Processing',
    requested: 'May 31, 2025 11:02 AM',
  },
  {
    id: 'EXP-2025-004',
    name: 'Under-sampled zones - May',
    format: 'GeoJSON',
    filters: 3,
    records: 512,
    status: 'Failed',
    requested: 'May 30, 2025 9:21 AM',
  },
];
